# https://gohugo.io/getting-started/configuration/#all-configuration-settings

# Slash works for both development and production.
baseurl: '/'
title: 上郷ノーティボーイズ
languageCode: ja
defaultContentLanguage: ja
paginate: 30
googleAnalytics: UA-177386393-1
enableRobotsTXT: true
hasCJKLanguage: true

params:
  description: 愛知県豊田市南部にある少年軟式野球チーム・上郷ノーティボーイズです。
  # Specify sections to pull recent posts from.
  mainSections:
    - blog
  recentPostCount: 6

# https://gohugo.io/content-management/menus/
menu:
  main:
    - identifier: team
      name: チーム
      url: '/team/'
      weight: 1
    - identifier: blog
      name: 記事
      url: '/blog/'
      weight: 2
    - identifier: about
      name: 活動
      url: '/about/'
      weight: 3
    - identifier: links
      name: リンク
      url: '/links/'
      weight: 9

# https://gohugo.io/content-management/image-processing/
imaging:
  quality: 100

# https://gohugo.io/content-management/taxonomies/
taxonomies:
  tag: tags

markup:
  goldmark:
    renderer:
      # This is a workdown so that we can embed HTML tags in a markdown file.
      # https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032
      unsafe: true
