# https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseURL: '/'
languageCode: ja
title: 上郷ノーティボーイズ
Copyright: 上郷ノーティボーイズ
paginate: 30
googleAnalytics: UA-177386393-1
enableRobotsTXT: true
hasCJKLanguage: true

# https://gohugo.io/variables/site/#the-siteparams-variable
params:
  logoImage: 'img/logo.svg'
  description: |
    私達は、愛知県豊田市南部にある少年軟式野球チーム・上郷ノーティボーイズです。野球を愛する少年・少女達の夢を育み、軟式野球を正しく指導し、体力向上と礼儀を養成します。また、親友同士の友情と交歓の場を与え、規則正しい明朗な少年・少女を育成することを目的としています。
  # Specify sections to pull recent posts from.
  mainSections:
    - blog
  recentPostCount: 6

# https://gohugo.io/content-management/menus
menu:
  main:
    - name: チーム
      url: '/team'
      weight: 1
    - name: 記事
      url: '/blog'
      weight: 2
    - name: リンク
      url: '/links'
      weight: 3

# https://gohugo.io/content-management/image-processing/
imaging:
  quality: 50

# https://gohugo.io/content-management/taxonomies/
taxonomies:
  tag: tags

# https://gohugo.io/news/0.60.0-relnotes/
markup:
  goldmark:
    renderer:
      unsafe: true
