# How to set up Netlify CMS for Hugo: https://www.netlifycms.org/docs/hugo
# Available options: https://www.netlifycms.org/docs/configuration-options
# Example: https://github.com/netlify/netlify-cms/blob/master/dev-test/config.yml
backend:
  name: git-gateway
  # git Gateway Error: Please ask your site administrator to reissue the Git Gateway token
  # https://community.netlify.com/t/git-gateway-error/12220/8
  repo: knbbaseball/website
  branch: master
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

# https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: 'site/content/img' # Folder where user uploaded files should go
public_folder: '/img' # Folder where the files uploaded by the media library will be accessed

site_url: https://knbbaseball.netlify.app
logo_url: https://user-images.githubusercontent.com/7563926/201543492-fac1a61c-9906-444c-a5d5-3dfdfb6d3568.png
locale: 'ja'
show_preview_links: false

collections: # A list of collections the CMS should be able to edit
  - name: blog # Used in routes, ie.: /admin/collections/:slug/edit
    label: 記事 # Used in the UI, ie.: "New Blog Post"
    folder: 'site/content/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}{{minute}}' # E.g. "2020-01-01-1234"
    editor: { preview: false }
    fields: # The fields each document in this collection have
      - {
        label: 日付,
        name: date,
        widget: datetime,
        format: 'YYYY-MM-DD HH:mm:ss ZZ', # Needed to avoid the following error in the CMS preview: "Objects are not valid as a React child"
        date_format: 'YYYY-MM-DD',
        time_format: 'HH:mm',
        picker_utc: true, # so users in all timezones will see the same date in the datetime picker
      }
      - { label: 題目, name: 'title', widget: 'string' }
      - { label: 説明, name: 'description', widget: 'text', required: false }
      - { label: タグ, name: 'tags', widget: 'list', required: false }
      - { label: 写真, name: 'image', widget: 'image', required: false }
      - { label: 本文, name: 'body', widget: 'markdown', required: false }
  - name: 'team' # Used in routes, ie.: /admin/collections/:slug/edit
    label: チーム # Used in the UI, ie.: "New Team"
    folder: 'site/content/team' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{fields.slug}}'
    editor: { preview: false }
    fields: # The fields each document in this collection have
      - {
        label: 日付,
        name: date,
        widget: datetime,
        format: 'YYYY-MM-DD HH:mm:ss ZZ', # Needed to avoid the following error in the CMS preview: "Objects are not valid as a React child"
        date_format: true,
        time_format: false,
        picker_utc: true, # so users in all timezones will see the same date in the datetime picker
      }
      - { label: スラッグ, name: 'slug', widget: 'string' }
      - { label: チーム名, name: 'title', widget: 'string' }
      - { label: タグ, name: 'tags', widget: 'list', required: false }
      - { label: 写真, name: 'image', widget: 'image', required: false }
      - { label: 本文, name: 'body', widget: 'markdown', required: false }
      - {
          label: 選手,
          name: players,
          widget: list,
          required: false,
          fields:
            [
              { label: 背番号, name: number, widget: string, required: false },
              { label: 名前, name: name, widget: string },
              { label: 学校, name: school, widget: string },
              { label: 投, name: threw, widget: string },
              { label: 打, name: batted, widget: string },
            ],
        }
      - {
          label: 監督・コーチ,
          name: coaches,
          widget: list,
          required: false,
          fields:
            [
              { label: 背番号, name: number, widget: string, required: false },
              { label: 名前, name: name, widget: string },
            ],
        }
      - {
        label: 試合結果,
        name: scores,
        widget: list,
        required: false,
        fields:
          [
            {
              label: 日付,
              name: date,
              widget: datetime,
              format: 'YYYY-MM-DD HH:mm:ss ZZ', # Needed to avoid the following error in the CMS preview: "Objects are not valid as a React child"
              date_format: true,
              time_format: false,
              picker_utc: true, # so users in all timezones will see the same date in the datetime picker
            },
            { label: 試合, name: name, widget: string, required: true },
            { label: 対戦相手, name: opponent, widget: string, required: false },
            { label: スコア, name: score, widget: string, required: false },
            { label: 勝敗, name: win, widget: string, required: false },
            { label: 備考, name: memo, widget: string, required: false },
          ],
      }
  - name: pages
    label: ページ
    editor: { preview: false }
    files:
      - file: 'site/content/_index.md'
        label: ホーム
        name: home
        fields:
          - { label: 写真, name: image, widget: image }
          - {
              label: 代表挨拶,
              name: blurb,
              widget: object,
              fields:
                [
                  { label: 本文, name: text, widget: text },
                  { label: 代表写真, name: gmImage, widget: image },
                  { label: 代表氏名, name: gmName, widget: string },
                ],
            }
          - { label: 動く文, name: banner, widget: string, required: false }
          - {
              label: スケジュール,
              name: schedule,
              widget: list,
              required: false,
              fields:
                [
                  { label: チーム, name: team, widget: string },
                  {
                    label: 日付,
                    name: date,
                    widget: datetime,
                    format: 'YYYY-MM-DD HH:mm:ss ZZ', # Needed to avoid the following error in the CMS preview: "Objects are not valid as a React child"
                    date_format: true,
                    time_format: false,
                    picker_utc: true, # so users in all timezones will see the same date in the datetime picker
                  },
                  { label: 時間, name: time, widget: string },
                  { label: 説明, name: description, widget: string },
                  { label: 場所, name: location_text, widget: string },
                  { label: 場所URL, name: location_url, widget: string, required: false },
                ],
            }
          - {
              label: お知らせ,
              name: info,
              widget: object,
              required: false,
              fields:
                [
                  { label: 題目, name: title, widget: string },
                  { label: 本文, name: content, widget: text },
                  { label: 写真, name: image, widget: image },
                  { label: リンク文, name: actionText, widget: string, required: false },
                  { label: リンクURL, name: actionUrl, widget: string, required: false },
                ],
            }
          - { label: 本文, name: 'body', widget: 'markdown', required: false }
      - file: 'site/content/links.md'
        label: リンク
        name: links
        fields:
          - { label: 'Hugo content type', name: 'type', widget: 'hidden', default: 'page' }
          - { label: 本文, name: body, widget: markdown }
